// ─────────────────────────────────────────────────────────────
//  IMPORTANT: This file is auto-generated by FlutterFire CLI.
//  Run this command in your project root to generate it:
//
//    flutterfire configure
//
//  Then replace this file with the generated one.
//  Full guide: https://firebase.flutter.dev/docs/cli
// ─────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      default: throw UnsupportedError('Unsupported platform');
    }
  }

  // ── Replace ALL values below with your real Firebase config ──

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd9-88ygq1I1OeUbbp2rxBvvRI9LrYseQ',
    appId: '1:695619749926:web:2335fcc6b3bdf55125fee7',
    messagingSenderId: '695619749926',
    projectId: 'rizznight-run',
    authDomain: 'rizznight-run.firebaseapp.com',
    storageBucket: 'rizznight-run.firebasestorage.app',
    measurementId: 'G-PMCC4V1496',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.rizznight.app',
  );
}